services:
  - type: web
    name: crypto-educator
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    root: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
